### ISSUE TITLE
이거는 왜 만든건가요?

### ISSUE THREAD

**Issue by namongk** [Monaegi/bbungsang-UsedBookStore#2]
https://github.com/Monaegi/bbungsang-UsedBookStore/blob/d0d1926edbbce8308d5e3a88adb662fbc1f77618/django_app/book/models/book.py#L51

**Comment by bbungsang** [comment]
네이버 API 책검색해서 텍스트를 가져오면 검색어에 해당하는 단어에 b태그가 달려서 옵니다. 그래서 그걸 걸러주는 함수입니다!
